# Generated by Django 3.0.3 on 2020-02-09 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200130_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-create_time', 'title'], 'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
    ]
