# Generated by Django 2.2.3 on 2020-04-02 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200229_1104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='views',
        ),
        migrations.AddField(
            model_name='post',
            name='views_num',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
